---
title: "Pivoting data from wide to tall and back"
author: "Melinda Higgins"
date: "3/17/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# show code
knitr::opts_chunk$set(echo = TRUE)
# compile Rmarkdown "knit" even if errors
knitr::opts_chunk$set(error = TRUE)

# make any table output 
# formatted as a table
library(printr)

# load dplyr for these examples
library(dplyr)
```

## Convert from TALL dataset to WIDE

```{r}
library(readr)
long1 <- read_csv("long1.csv")
long1
```

```{r}
library(tidyr)
long1_to_wide <- long1 %>%
  tidyr::pivot_wider(id_cols = id,
                     names_from = time,
                     values_from = c(bmi, satis))

long1_to_wide
```

## Go from WIDE to LONG

```{r}
wide1 <- read_csv("wide1.csv")
wide1
```

This code uses "regular expressions" to parse the "patterns" of variable names.

_This is my guess of why/how this works..._

* `()` identifies a grouping
* `.` identifies any characters except new line
* `+` identifies a quantifier (number)

Learn more with these cheatsheets on "regex"

* https://cheatography.com/davechild/cheat-sheets/regular-expressions/
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet

```{r}
wide1_to_long1 <- wide1 %>%
  tidyr::pivot_longer(cols = bmi1:satis3)

wide1_to_long1 

wide1_to_long2 <- wide1 %>%
  tidyr::pivot_longer(cols = bmi1:satis3,
                      names_to = c(".value", "time"),
                      names_pattern = "(.+)(.+)")

wide1_to_long2
```

